Systree/Systree/Controllers/PlantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Systree.Models;

namespace Systree.Controllers
{
    public class PlantController : Controller
    {
        private systreeDBEntities1 db = new systreeDBEntities1();

        public ActionResult Tips()
        {
            return View();
        }

        // GET: Plant
        public ActionResult Index()
        {
            return View(db.Planta.ToList());
        }

        // GET: Plant/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Redirect);
            }
            Planta planta = db.Planta.Find(id);
            if (planta == null)
            {
                return HttpNotFound();
            }
            return View(planta);
        }

        // GET: Plant/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Plant/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Tipo,Nombre,Longitud_promedio,Temporada,Luz_exposicion,Riego,Tipo_suelo,Otros")] Planta planta)
        {
            if (ModelState.IsValid)
            {
                db.Planta.Add(planta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(planta);
        }

        // GET: Plant/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planta planta = db.Planta.Find(id);
            if (planta == null)
            {
                return HttpNotFound();
            }
            return View(planta);
        }

        // POST: Plant/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Tipo,Nombre,Longitud_promedio,Temporada,Luz_exposicion,Riego,Tipo_suelo,Otros")] Planta planta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(planta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(planta);
        }

        // GET: Plant/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planta planta = db.Planta.Find(id);
            if (planta == null)
            {
                return HttpNotFound();
            }
            return View(planta);
        }

        // POST: Plant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Planta planta = db.Planta.Find(id);
            db.Planta.Remove(planta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Systree/Systree/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SysTree</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" href="~/resources/logo.png" />
    <link href="~/Style/StyleSheet1.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" media="screen" runat="server">
</head>
<body>

    @{
        Array breadcrumbPath = HttpContext.Current.Request.Url.AbsolutePath.Split('/');
        ViewBag.route = breadcrumbPath;

        string relativePath(int currentPath)
        {
            string route = "";
            for (int i = 1; i <= currentPath; i++)
                route += "/" + breadcrumbPath.GetValue(i);

            return route;
        }
    }

    <!-- ***************************************************************************************** -->
    <!-- ********************************** Menu ************************************************* -->
    <!-- ***************************************************************************************** -->


    <nav class="navbar navbar-expand-lg navbar-dark px-5" id="navbar">
        <a class="navbar-brand logohover pl-md-5" href="~/Home/Dashboard">
            <img src="~/resources/Logo.png" class="align-top logo" alt="Logo">
            &ensp;SysTree
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center pr-md-5" id="navbarNavDropdown">
            <ul class="navbar-nav">
                @if (Session["UserName"] != null)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Tablero", "Dashboard/0", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Plantas
                        </a>
                        <div class="dropdown-menu bg-dark text-dark pl-3" aria-labelledby="navbarDropdownMenuLink" id="subMenu">
                            @Html.ActionLink("Glosario", "Index", "Plant", new { area = "" }, new { @class = "nav-link" })
                            @Html.ActionLink("Consejos", "Tips", "Plant", new { area = "" }, new { @class = "nav-link" })
                        </div>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle border rounded" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user"></i> @Session["UserName"]
                        </a>
                        <div class="dropdown-menu bg-dark text-dark pl-3" aria-labelledby="navbarDropdownMenuLink" id="subMenu">
                            <a href="~/Profile/Details/@Session["UserId"]" class="nav-link">Mi Perfil</a>
                            @Html.ActionLink("Cerrar Sesión", "Logout", "Home", new { area = "" }, new { @class = "nav-link" })
                        </div>
                    </li>
                }

                else
                {
                    <li class="nav-item">
                        @Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="navbar-item">
                        @Html.ActionLink("Iniciar Sesión", "Login", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="navbar-item">
                        @Html.ActionLink("Registrarse", "Signup", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                }
            </ul>
        </div>
    </nav>


    <section class="container body-content">
        <article>
            <ol class="breadcrumb mb-0">
                @for (int i = 1; i < ViewBag.route.Length; i++)
                {
                    string route = relativePath(i);
                    <li class="breadcrumb-item"><a>@ViewBag.route[i]</a></li>
                }
            </ol>
        </article>
        <article style="margin-top: -20px;">
            @RenderBody()
        </article>
    </section>


    <hr />
    <footer class="p-4 text-center">
        <span class="lead">SysTree - &copy; @DateTime.Now.Year</span>
    </footer>


    <div class="se-pre-con">
        <div class="spinner-grow text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
        <div class="spinner-grow bg-secondary mb-3" role="status">
        </div>
        <div class="spinner-grow text-danger" role="status">
            <span class="sr-only">Loading...</span>
        </div>
        <div class="mx-auto" role="status">
            <img src="~/resources/logo.png" class="spinner-grow bg-transparent text-light" />
            <span class="align-top lead font-weight-normal">SysTree</span>
            <img src="~/resources/logo.png" class="spinner-grow bg-transparent" />
        </div>
        <div class="spinner-grow text-success mb-3" role="status">
            <span class="sr-only">Loading...</span>
        </div>
        <div class="spinner-grow text-warning mt-3" role="status">
        </div>
        <div class="spinner-grow text-dark mb-3" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

    <style>
        /** Loader **/
        .se-pre-con {
            top: 50%;
            left: 50%;
            position: fixed;
            text-align: center;
            border-radius: 50%;
            border: 1px solid purple;
            transform: translate(-50%, -50%);
            background: url(images/loader-64x/Preloader_2.gif) center no-repeat #fff;
        }
    </style>

    <script src="~/Style/JavaScript.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>

    <script>
        /** Loader **/
        // Wait for window load
        $(window).load(function () {
            // Animate loader off screen
            $(".se-pre-con").fadeOut("slow");
        });
    </script>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>